/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ortega.miriam.ui;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import ortega.miriam.controladores.AbonosJpaController;
import ortega.miriam.controladores.CuentasCxPJpaController;
import ortega.miriam.entidades.Abonos;
import ortega.miriam.entidades.CuentasCxP;

/**
 *
 * @author macbookpro
 */
public class AbonosForm extends javax.swing.JDialog {

    private CuentasCxP cuenta;
    public AbonosJpaController abonoController;
    public static CuentasCxPJpaController ctaController;

    /**
     * Creates new form ClientForm
     *
     * @param parent
     * @param modal
     * @param cuenta
     */
    public AbonosForm(java.awt.Frame parent, boolean modal,
            CuentasCxP cuenta) {
        super(parent, modal);
        abonoController = new AbonosJpaController();
        ctaController = new CuentasCxPJpaController();

        this.cuenta = cuenta;
        initComponents();
        llenarDatos();
    }

    private void llenarDatos() {
        if (cuenta.getTipo().equals("COBRAR")) {
            entidadLbl.setText(cuenta.getFacturaId().
                    getIdcliente().getEntidadid().getNombres());
        } else {

            entidadLbl.setText(cuenta.getFacturaId().
                    getIdproveedor().getEntidadid().getNombres());
        }
        this.totalLbl.setText("$ " + cuenta.getTotal());

        if (this.cuenta.getEstado().equals("PAGADA")) {
            guardarBtn.setEnabled(false);
        } else {
            guardarBtn.setEnabled(true);
        }
        saldoLbl.setText("$ " +cuenta.getSaldo().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("facturacionMueblesDesktopPU").createEntityManager();
        getRowsQuery = java.beans.Beans.isDesignTime() ? null : entityManager1.createQuery("SELECT a FROM Abonos a where a.cuenta =:cuenta");
        getRowsQuery.setParameter("cuenta", this.cuenta);
        list1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : getRowsQuery.getResultList();
        rowCountQuery = java.beans.Beans.isDesignTime() ? null : entityManager1.createQuery("SELECT count(a) FROM Abonos a where a.cuenta =:cuenta");
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cantidadTxt = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        entidadLbl = new javax.swing.JLabel();
        Saldo = new javax.swing.JLabel();
        saldoLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        rowCountQuery.setParameter("cuenta", this.cuenta);

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Abonos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 14))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Total: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 60, 160, 16);
        jPanel1.add(cantidadTxt);
        cantidadTxt.setBounds(180, 120, 160, 28);

        guardarBtn.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        guardarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/save.png"))); // NOI18N
        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(guardarBtn);
        guardarBtn.setBounds(360, 110, 150, 40);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cantidad:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 120, 127, 16);

        totalLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        totalLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalLbl.setText(" ");
        jPanel1.add(totalLbl);
        totalLbl.setBounds(190, 60, 430, 16);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cliente/Proveedor: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 30, 160, 16);

        entidadLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        entidadLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        entidadLbl.setText(" ");
        jPanel1.add(entidadLbl);
        entidadLbl.setBounds(190, 30, 430, 16);

        Saldo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Saldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Saldo.setText("Saldo:");
        jPanel1.add(Saldo);
        Saldo.setBounds(10, 90, 160, 16);

        saldoLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        saldoLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        saldoLbl.setText(" ");
        jPanel1.add(saldoLbl);
        saldoLbl.setBounds(190, 90, 430, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 660, 170);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagos realizados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 14))); // NOI18N
        jPanel2.setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list1, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${saldo}"));
        columnBinding.setColumnName("Saldo");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 630, 180);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 210, 670, 210);

        bindingGroup.bind();

        setBounds(0, 0, 699, 463);
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        String texto = cantidadTxt.getText();
        //validacion de monto
        BigDecimal quantity = BigDecimal.ZERO;
        try {
            quantity = new BigDecimal(texto);
            if (quantity.compareTo(BigDecimal.ZERO) == -1) {
                JOptionPane.showMessageDialog(this, "Ingrese un valor mayor a cero",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            //si el valor es mayor que el saldo que se debe
             if (quantity.compareTo(cuenta.getSaldo()) == 1) {
                JOptionPane.showMessageDialog(this, "El valor a pagar es mayor "
                        + "que el saldo de la deuda",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor válido",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try { 
            Abonos abono = new Abonos();
            abono.setFecha(new Date());
            abono.setValor(quantity);
            abono.setCuenta(cuenta);
            BigDecimal saldo = cuenta.getSaldo().subtract(quantity);
            abono.setSaldo(saldo);
            abonoController.create(abono);
            //actualizar la cuenta
            cuenta.setSaldo(saldo);
            if (saldo.compareTo(BigDecimal.ZERO) == 0) {
                cuenta.setEstado("PAGADA");
                guardarBtn.setEnabled(false);
            }
            ctaController.edit(cuenta);
            String tipoMensaje = "El registro ha sido actualizado con éxito";
            String tituloMensaje = "Información";
            int tipoMens = JOptionPane.INFORMATION_MESSAGE;
            JOptionPane.showMessageDialog(this, tipoMensaje, tituloMensaje, tipoMens);
            actualizar();
            this.cantidadTxt.setText("");
            saldoLbl.setText("$ " +cuenta.getSaldo().toString());
            cxcPanel.actualizar();
        } catch (Exception e) { 
        }


    }//GEN-LAST:event_guardarBtnActionPerformed

    public static void actualizar() {
        //ilst1.clear();
        List<Abonos> abonos = getList();
        for (Abonos abono : abonos) {
            entityManager1.refresh(abono);
        }
        list1 = abonos; 
        generarTabla();
    }

    private static void generarTabla() {
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list1, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${saldo}"));
        columnBinding.setColumnName("Saldo");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        jTableBinding.bind();
    }

    public static List<Abonos> getList() {
        List<Abonos> abonos = new ResultListJPA<>(rowCountQuery,
                getRowsQuery);
        return abonos;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AbonosForm dialog = new AbonosForm(new javax.swing.JFrame(),
                        true, new CuentasCxP());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public CuentasCxP getCuenta() {
        return cuenta;
    }

    public void setCuenta(CuentasCxP cuenta) {
        this.cuenta = cuenta;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Saldo;
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JLabel entidadLbl;
    public static javax.persistence.EntityManager entityManager1;
    public static javax.persistence.Query getRowsQuery;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static java.util.List<Abonos> list1;
    public static javax.persistence.Query rowCountQuery;
    private javax.swing.JLabel saldoLbl;
    private javax.swing.JLabel totalLbl;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
