/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ortega.miriam.ui;
 
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.BindingGroup;
import ortega.miriam.controladores.GrupoJpaController;
import ortega.miriam.controladores.exceptions.IllegalOrphanException;
import ortega.miriam.controladores.exceptions.NonexistentEntityException;
import ortega.miriam.entidades.Grupo;
import ortega.miriam.entidades.Rol; 
import static ortega.miriam.ui.RolPanel.controlador;
import static ortega.miriam.ui.RolPanel.entityManager1;
import static ortega.miriam.ui.RolPanel.getList;
import static ortega.miriam.ui.RolPanel.getRowsQuery;
import static ortega.miriam.ui.RolPanel.jTable1;
import static ortega.miriam.ui.RolPanel.list1;

/**
 *
 * @author macbookpro
 */
public class GruposPanel extends javax.swing.JPanel {

    public static GrupoJpaController controlador; 

    static void crear(Grupo grupo) {
        String tipoMensaje = "";
        String tituloMensaje = "";
        int tipoMens = 0;
        controlador.create(grupo);
        tipoMensaje = "El registro ha sido actualizado con éxito";
        tituloMensaje = "Información";
        tipoMens = JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(null, tipoMensaje, tituloMensaje, tipoMens);
        actualizar();
    }

    static void editar(Grupo grupo) {
        String tipoMensaje = "";
        String tituloMensaje = "";
        int tipoMens = 0;
        try { 
            controlador.edit(grupo);
            tipoMensaje = "El registro ha sido actualizado con éxito";
            tituloMensaje = "Información";
            tipoMens = JOptionPane.INFORMATION_MESSAGE;
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(GruposPanel.class.getName()).log(Level.SEVERE, null, ex);
            tipoMensaje = "Existe un problema al modificar el registro";
            tituloMensaje = "Error";
            tipoMens = JOptionPane.ERROR_MESSAGE;
        } catch (Exception ex) {
            Logger.getLogger(GruposPanel.class.getName()).log(Level.SEVERE, null, ex);
            tipoMensaje = "Existe un problema al modificar el registro";
            tituloMensaje = "Error";
            tipoMens = JOptionPane.ERROR_MESSAGE;
        }
        JOptionPane.showMessageDialog(null, tipoMensaje, tituloMensaje, tipoMens);
        actualizar();
    }
    /**
     * Creates new form GruposPanel
     */
    public GruposPanel() {
        initComponents();
        controlador = new GrupoJpaController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("facturacionMueblesDesktopPU").createEntityManager();
        getRowsQuery = java.beans.Beans.isDesignTime() ? null : entityManager1.createQuery("Select g from Grupo g");
        rowCountQuery = java.beans.Beans.isDesignTime() ? null : entityManager1.createQuery("Select count(g) from Grupo g");
        list1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : getRowsQuery.getResultList();
        list1=getList();
        jPanel1 = new javax.swing.JPanel();
        eliminarBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();
        nuevoBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grupos de productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 24))); // NOI18N
        jPanel1.setLayout(null);

        eliminarBtn.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        eliminarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/delete.png"))); // NOI18N
        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarBtn);
        eliminarBtn.setBounds(400, 50, 120, 50);

        editarBtn.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        editarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/edit.png"))); // NOI18N
        editarBtn.setText("Editar");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editarBtn);
        editarBtn.setBounds(280, 50, 120, 50);

        nuevoBtn.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        nuevoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/add1.png"))); // NOI18N
        nuevoBtn.setText("Nuevo");
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nuevoBtn);
        nuevoBtn.setBounds(160, 50, 120, 50);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list1, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 500, 158);

        add(jPanel1);
        jPanel1.setBounds(20, 30, 540, 290);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        Grupo r = getIndex();
        if (r != null) {
            String message = "Desea eliminar el registro?";
            String title = "Confirmar eliminación";
            int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                String tipoMensaje = "";
                String tituloMensaje = "";
                int tipoMens = 0;
                try {
                    controlador.destroy(r.getId());
                    tipoMensaje = "El registro ha sido actualizado con éxito";
                    tituloMensaje = "Información";
                    tipoMens = JOptionPane.INFORMATION_MESSAGE;
                } catch (NonexistentEntityException ex) {
                    Logger.getLogger(RolPanel.class.getName()).log(Level.SEVERE, null, ex);
                    tipoMensaje = "Existe un problema al eliminar el registro";
                    tituloMensaje = "Error";
                    tipoMens = JOptionPane.ERROR_MESSAGE;
                }   

                JOptionPane.showMessageDialog(null, tipoMensaje, tituloMensaje, tipoMens);
               actualizar();
            }
        }
    }//GEN-LAST:event_eliminarBtnActionPerformed

    
    public static void actualizar() { 
        List<Grupo> grupos = getList();  
        for (Grupo grupo : grupos) {
            entityManager1.refresh(grupo);
        }
        list1 = grupos;

        BindingGroup bindingGroup = new org.jdesktop.beansbinding.BindingGroup();
        org.jdesktop.swingbinding.JTableBinding jTableBinding
                = org.jdesktop.swingbinding.SwingBindings.
                createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list1, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding
                = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(
                org.jdesktop.beansbinding.ELProperty.create("${nombre}"));
        columnBinding.setColumnName("Nombre");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        bindingGroup.bind();
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(240);
        }
    }
    
    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        Grupo r = getIndex();
        if (r != null) {
            abrirFormulario(r);
        }
    }//GEN-LAST:event_editarBtnActionPerformed

     private final Grupo getIndex() {
        int index = jTable1.getSelectedRow();
        Grupo grupo = null;
        if (index != -1) {
            grupo = list1.get(index);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        return grupo;
    }
    private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
        abrirFormulario(new Grupo());
    }//GEN-LAST:event_nuevoBtnActionPerformed

 private void abrirFormulario(final Grupo grupo) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GrupoForm dialog = new GrupoForm(new javax.swing.JFrame(), true, grupo);
                dialog.setLocationRelativeTo(null);
               
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
 
  public static List<Grupo> getList() {
        List<Grupo> grupos = new ResultListJPA<>(rowCountQuery, getRowsQuery);
        return grupos;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarBtn;
    private javax.swing.JButton eliminarBtn;
    public static javax.persistence.EntityManager entityManager1;
    public static javax.persistence.Query getRowsQuery;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static java.util.List<Grupo> list1;
    private javax.swing.JButton nuevoBtn;
    private static javax.persistence.Query rowCountQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
