/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ortega.miriam.ui;

/**
 *
 * @author macbookpro
 */
public class PanelIconos extends javax.swing.JPanel {

    /**
     * Creates new form PanelIconos
     */
    public PanelIconos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruposIcon = new javax.swing.JLabel();
        gruposLbl = new javax.swing.JLabel();
        clientesIcon = new javax.swing.JLabel();
        clientesLbl = new javax.swing.JLabel();
        usuariosIcon = new javax.swing.JLabel();
        usuariosLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        gruposIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/grupos.jpg"))); // NOI18N
        gruposIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gruposIconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gruposIconMouseEntered(evt);
            }
        });

        gruposLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        gruposLbl.setForeground(new java.awt.Color(255, 255, 255));
        gruposLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gruposLbl.setText("GRUPOS");
        gruposLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gruposLblMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gruposLblMouseEntered(evt);
            }
        });

        clientesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/clientes.png"))); // NOI18N

        clientesLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        clientesLbl.setForeground(new java.awt.Color(255, 255, 255));
        clientesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientesLbl.setText("CLIENTES");

        usuariosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/usuarios.jpg"))); // NOI18N

        usuariosLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        usuariosLbl.setForeground(new java.awt.Color(255, 255, 255));
        usuariosLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuariosLbl.setText("USUARIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gruposLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gruposIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clientesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(clientesLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuariosIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usuariosLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuariosIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(clientesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gruposIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gruposLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuariosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(299, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gruposLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gruposLblMouseEntered
        gruposLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_gruposLblMouseEntered

    private void gruposIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gruposIconMouseEntered

        gruposLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_gruposIconMouseEntered

    private void gruposIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gruposIconMouseExited

        gruposLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_gruposIconMouseExited

    private void gruposLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gruposLblMouseExited
         gruposLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_gruposLblMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientesIcon;
    private javax.swing.JLabel clientesLbl;
    private javax.swing.JLabel gruposIcon;
    private javax.swing.JLabel gruposLbl;
    private javax.swing.JLabel usuariosIcon;
    private javax.swing.JLabel usuariosLbl;
    // End of variables declaration//GEN-END:variables
}
