/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ortega.miriam.ui;

import java.util.List;
import javax.swing.JOptionPane;
import ortega.miriam.controladores.RolJpaController;
import ortega.miriam.entidades.Rol;

/**
 *
 * @author macbookpro
 */
public class RolForm extends javax.swing.JDialog {

    RolJpaController controlador;
    public Rol rol;

    /**
     * Creates new form RolDialog
     */
    public RolForm(java.awt.Frame parent, boolean modal, Rol rol) {
        super(parent, modal);
        this.rol = rol;
        initComponents();
        controlador = new RolJpaController();
        fijarRol();
    }

    private void fijarRol() {
        rolNombre.setText(rol.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rolNombre = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear/editar Rol");
        getContentPane().setLayout(null);
        getContentPane().add(rolNombre);
        rolNombre.setBounds(10, 10, 261, 40);

        guardar.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/save.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar);
        guardar.setBounds(273, 6, 130, 44);

        setBounds(0, 0, 410, 81);
    }// </editor-fold>//GEN-END:initComponents

    private boolean esValido() {
        boolean valido = true;
        Rol buscar = new Rol();
        buscar.setNombre(this.rolNombre.getText());
        List<Rol> roles = controlador.find(buscar);
        if (roles.size() > 0) {
            valido = false;
            JOptionPane.showMessageDialog(this, "Ya existe un registro similar ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return valido;
    }
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed

        if (!esValido()) {
            return;
        }

        rol.setNombre(this.rolNombre.getText());
        
        //guardar
        if (rol.getId() == null) {
            RolPanel.crear(rol); 
        } else {
            RolPanel.editar(rol); 
        }
 
        this.dispose(); 
    }//GEN-LAST:event_guardarActionPerformed

    public static void main(String[]args){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Rol rol = new Rol();
                rol.setEditar(false);
                RolForm dialog = new RolForm(new javax.swing.JFrame(), true, rol);
                dialog.setLocationRelativeTo(null);
               
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardar;
    private javax.swing.JTextField rolNombre;
    // End of variables declaration//GEN-END:variables
}
