/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ortega.miriam.ui;

import javax.swing.JLabel;

/**
 *
 * @author macbookpro
 */
public class Secretaria extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicial
     */
    public Secretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        container = new javax.swing.JPanel();
        clientesIcon = new javax.swing.JLabel();
        clientesLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        compraLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ventaLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Facturación");
        getContentPane().setLayout(null);

        container.setBackground(new java.awt.Color(51, 51, 51));
        container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        clientesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/clientes.png"))); // NOI18N
        clientesIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientesIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientesIconMouseExited(evt);
            }
        });

        clientesLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        clientesLbl.setForeground(new java.awt.Color(255, 255, 255));
        clientesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientesLbl.setText("CLIENTES");
        clientesLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientesLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientesLblMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/compra.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        compraLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        compraLbl.setForeground(new java.awt.Color(255, 255, 255));
        compraLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compraLbl.setText("FACTURAS DE COMPRA");
        compraLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compraLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compraLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                compraLblMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/ventas1.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        ventaLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ventaLbl.setForeground(new java.awt.Color(255, 255, 255));
        ventaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventaLbl.setText("FACTURAS DE VENTA");
        ventaLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventaLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ventaLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ventaLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel4))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(compraLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ventaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(622, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(clientesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clientesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compraLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ventaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(435, Short.MAX_VALUE))
        );

        getContentPane().add(container);
        container.setBounds(0, 0, 1350, 640);

        jMenu3.setText("Inicio");
        jMenu3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jMenu3.setMaximumSize(new java.awt.Dimension(100, 32767));

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Ventana inicial");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Administración");
        jMenu1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jMenu1.setMaximumSize(new java.awt.Dimension(160, 32767));

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Compras");
        jMenu2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jMenu2.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMenuItem5.setText("Facturas de compra");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Ventas");
        jMenu4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jMenu4.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMenuItem6.setText("Facturas de venta");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1345, 699));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirRoles() {
        container.removeAll();
        RolPanel demo = new RolPanel();
        container.add(demo);
        demo.setBounds(0, 0, 1020, 559);
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        abrirClientes();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void abrirClientes() {
        container.removeAll();
        ClientePanel demo = new ClientePanel();
        container.add(demo);
        demo.setBounds(0, 8, 1000, 600);
    }
    private void clientesIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesIconMouseEntered
        clientesLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_clientesIconMouseEntered

    private void clientesLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesLblMouseEntered
        clientesLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_clientesLblMouseEntered

    private void clientesIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesIconMouseExited
        clientesLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_clientesIconMouseExited

    private void clientesLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesLblMouseExited
        clientesLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_clientesLblMouseExited

    private void clientesLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesLblMouseClicked
        abrirClientes();
    }//GEN-LAST:event_clientesLblMouseClicked

    private void clientesIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesIconMouseClicked
        abrirClientes();
    }//GEN-LAST:event_clientesIconMouseClicked

    private void abrirProductos() {
        container.removeAll();
        ProductoPanel demo = new ProductoPanel();
        container.add(demo);
        demo.setBounds(0, 0, 1024, 600);
    }

    private void abrirProveedores() {
        container.removeAll();
        ProveedorPanel demo = new ProveedorPanel();
        container.add(demo);
        demo.setBounds(0, 0, 900, 800);
    }
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        abrirFacturaCompra();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void abrirFacturaCompra() {
        container.removeAll();
        facturaCompraPanel demo = new facturaCompraPanel();
        container.add(demo);
        demo.setBounds(0, 0, 880, 642);
    }
    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        compraLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        compraLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void compraLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compraLblMouseClicked
        abrirFacturaCompra();
    }//GEN-LAST:event_compraLblMouseClicked

    private void compraLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compraLblMouseExited
        compraLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_compraLblMouseExited

    private void compraLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compraLblMouseEntered
        compraLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_compraLblMouseEntered

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        mainWindow();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        abrirFacturaCompra();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        abrirFacturaVenta();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        abrirFacturaVenta();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        ventaLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        ventaLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void ventaLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaLblMouseClicked
        abrirFacturaVenta();
    }//GEN-LAST:event_ventaLblMouseClicked

    private void ventaLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaLblMouseExited
        ventaLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_ventaLblMouseExited

    private void ventaLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventaLblMouseEntered
        ventaLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_ventaLblMouseEntered

    private void abrirFacturaVenta() {
        container.removeAll();
        facturaVentaPanel demo = new facturaVentaPanel();
        container.add(demo);
        demo.setBounds(0, 0, 900, 642);
    }

    private void abrirGrupos() {
        container.removeAll();
        GruposPanel demo = new GruposPanel();
        container.add(demo);
        demo.setBounds(0, 0, 900, 600);
    }

    private void abrirUsuarios() {
        container.removeAll();
        UsuarioPanel demo = new UsuarioPanel();
        container.add(demo);
        demo.setBounds(0, 0, 800, 600);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Secretaria frame = new Secretaria();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }

    public void mainWindow() {
        container.removeAll();

        buttonGroup1 = new javax.swing.ButtonGroup();
        container = new javax.swing.JPanel();
        clientesIcon = new javax.swing.JLabel();
        clientesLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        compraLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ventaLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Facturación");
        getContentPane().setLayout(null);

        container.setBackground(new java.awt.Color(51, 51, 51));
        container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        clientesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/clientes.png"))); // NOI18N
        clientesIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesIconMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientesIconMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientesIconMouseExited(evt);
            }
        });

        clientesLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        clientesLbl.setForeground(new java.awt.Color(255, 255, 255));
        clientesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientesLbl.setText("CLIENTES");
        clientesLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesLblMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientesLblMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientesLblMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/compra.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        compraLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        compraLbl.setForeground(new java.awt.Color(255, 255, 255));
        compraLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compraLbl.setText("FACTURAS DE COMPRA");
        compraLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compraLblMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                compraLblMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                compraLblMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/ventas1.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        ventaLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ventaLbl.setForeground(new java.awt.Color(255, 255, 255));
        ventaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventaLbl.setText("FACTURAS DE VENTA");
        ventaLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventaLblMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ventaLblMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                ventaLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
                containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(clientesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clientesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(containerLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel4))
                                .addGroup(containerLayout.createSequentialGroup()
                                        .addComponent(compraLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ventaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(622, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
                containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(containerLayout.createSequentialGroup()
                                        .addComponent(clientesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(clientesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(containerLayout.createSequentialGroup()
                                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(compraLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ventaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(435, Short.MAX_VALUE))
        );

        getContentPane().add(container);
        container.setBounds(0, 0, 1350, 640);

        jMenu3.setText("Inicio");
        jMenu3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jMenu3.setMaximumSize(new java.awt.Dimension(100, 32767));

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Ventana inicial");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Administración");
        jMenu1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jMenu1.setMaximumSize(new java.awt.Dimension(160, 32767));

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Compras");
        jMenu2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jMenu2.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMenuItem5.setText("Facturas de compra");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Ventas");
        jMenu4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jMenu4.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMenuItem6.setText("Facturas de venta");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1345, 699));
        setLocationRelativeTo(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel clientesIcon;
    private javax.swing.JLabel clientesLbl;
    private javax.swing.JLabel compraLbl;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JLabel ventaLbl;
    // End of variables declaration//GEN-END:variables

}
