/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ortega.miriam.ui;

import javax.swing.JLabel;

/**
 *
 * @author macbookpro
 */
public class VentanaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        container = new javax.swing.JPanel();
        usuariosIcon = new javax.swing.JLabel();
        usuariosLbl = new javax.swing.JLabel();
        clientesIcon = new javax.swing.JLabel();
        clientesLbl = new javax.swing.JLabel();
        gruposIcon = new javax.swing.JLabel();
        gruposLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Facturación");
        setResizable(false);
        getContentPane().setLayout(null);

        container.setBackground(new java.awt.Color(51, 51, 51));
        container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        usuariosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/usuarios.jpg"))); // NOI18N
        usuariosIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuariosIconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuariosIconMouseEntered(evt);
            }
        });

        usuariosLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        usuariosLbl.setForeground(new java.awt.Color(255, 255, 255));
        usuariosLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuariosLbl.setText("USUARIOS");
        usuariosLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuariosLblMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuariosLblMouseEntered(evt);
            }
        });

        clientesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/clientes.png"))); // NOI18N
        clientesIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientesIconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientesIconMouseEntered(evt);
            }
        });

        clientesLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        clientesLbl.setForeground(new java.awt.Color(255, 255, 255));
        clientesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientesLbl.setText("CLIENTES");
        clientesLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientesLblMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientesLblMouseEntered(evt);
            }
        });

        gruposIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ortega/miriam/imagenes/grupos.jpg"))); // NOI18N
        gruposIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gruposIconMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gruposIconMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gruposIconMouseEntered(evt);
            }
        });

        gruposLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        gruposLbl.setForeground(new java.awt.Color(255, 255, 255));
        gruposLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gruposLbl.setText("GRUPOS");
        gruposLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gruposLblMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gruposLblMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gruposLblMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gruposLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gruposIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuariosIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usuariosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clientesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(404, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clientesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuariosIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gruposIcon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gruposLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuariosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(407, Short.MAX_VALUE))
        );

        getContentPane().add(container);
        container.setBounds(0, 6, 950, 600);

        jMenu1.setText("Administración");

        jMenuItem1.setText("Roles");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Usuarios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventario");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 967, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        abrirRoles();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void abrirRoles() { 
        container.removeAll();
        RolPanel demo = new RolPanel();
        container.add(demo);
        demo.setBounds(0, 8, 600, 600); 
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        abrirClientes();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    private void abrirClientes(){
        container.removeAll();
        ClientePanel demo = new ClientePanel();
        container.add(demo);
        demo.setBounds(0, 8, 1000, 600);
    }
    private void gruposIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gruposIconMouseExited

        gruposLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_gruposIconMouseExited

    private void gruposIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gruposIconMouseEntered

        gruposLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_gruposIconMouseEntered

    private void gruposLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gruposLblMouseExited
        gruposLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_gruposLblMouseExited

    private void gruposLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gruposLblMouseEntered
        gruposLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_gruposLblMouseEntered

    private void usuariosIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosIconMouseEntered
        usuariosLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_usuariosIconMouseEntered

    private void usuariosLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosLblMouseEntered
        usuariosLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_usuariosLblMouseEntered

    private void usuariosIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosIconMouseExited
        usuariosLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_usuariosIconMouseExited

    private void usuariosLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosLblMouseExited
        usuariosLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_usuariosLblMouseExited

    private void clientesIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesIconMouseEntered
        clientesLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_clientesIconMouseEntered

    private void clientesLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesLblMouseEntered
        clientesLbl.setForeground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_clientesLblMouseEntered

    private void clientesIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesIconMouseExited
        clientesLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_clientesIconMouseExited

    private void clientesLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesLblMouseExited
        clientesLbl.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_clientesLblMouseExited

    private void gruposIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gruposIconMouseClicked
        abrirRoles();
    }//GEN-LAST:event_gruposIconMouseClicked

    private void gruposLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gruposLblMouseClicked
        abrirRoles();
    }//GEN-LAST:event_gruposLblMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        abrirUsuarios();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void abrirUsuarios(){
        container.removeAll();
        UsuarioPanel demo = new UsuarioPanel();
        container.add(demo);
        demo.setBounds(0, 8, 800, 600); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel clientesIcon;
    private javax.swing.JLabel clientesLbl;
    private javax.swing.JPanel container;
    private javax.swing.JLabel gruposIcon;
    private javax.swing.JLabel gruposLbl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel usuariosIcon;
    private javax.swing.JLabel usuariosLbl;
    // End of variables declaration//GEN-END:variables
}
